export const products = [
  {
    id: 1,
    CatId: 5059,
    MainCatId: 5000,
    SubCatId: 5050,
    slug: "/1/5059/wiwvovani-maradmwvane/wiwvovani-maradmwvane/kviparosi/kviparosi-da-tuia-cocxali-Robis-gasaSeneblad",
    img: "product_1.webp",
    images: [
      "product_1.webp",
      "product_2.webp",
      "product_3.webp",
      "product_4.webp",
    ],
    title: "კვიპაროსი და ტუია ცოცხალი ღობის გასაშენებლად",
    seoTitle: "kviparosi-da-tuia-cocxali-Robis-gasaSeneblad",
    LocId: 2,
    SellerType: 3,
    viewCount: Math.floor(Math.random() * 100) + 1,
    price: Math.floor(Math.random() * 150) + 1,
    description:
      "საოჯახო ადგილის წინასწარ გაზიარება გავლილი ინდივიდუალური მატიანი თხელიანი.",
    createdAt: new Date(),
    author: {
      firstName: "გურანდუხტი",
      role: "ფიზიკური პირი",
      phoneNumber: "+995-519-55-66-41",
    },
  },
  {
    id: 2,
    CatId: 4103,
    MainCatId: 4000,
    SubCatId: 4100,
    slug: "/2/4103/yvavilebi/qotnis-yvavilebi/aloe/aloe-vera",
    img: "product_2.webp",
    images: [
      "product_2.webp",
      "product_5.webp",
      "product_3.webp",
      "product_4.webp",
    ],
    title: "ალოე ვერა",
    seoTitle: "aloe-vera",
    LocId: 3,
    SellerType: 2,
    viewCount: Math.floor(Math.random() * 100) + 1,
    price: Math.floor(Math.random() * 100) + 1,
    description:
      "სურვილებისა და საკუთარი სტანდარტების გაზიარება მოწმობილია ჩვენი მაღაზიიდან.",
    createdAt: new Date(),
    author: {
      firstName: "ბრენდა",
      role: "ფიზიკური პირი",
      phoneNumber: "+995-519-55-66-42",
    },
    isFavorite: true,
  },
  {
    id: 3,
    CatId: 4108,
    MainCatId: 4000,
    SubCatId: 4100,
    slug: "/3/4108/yvavilebi/qotnis-yvavilebi/sxva/baraqis-xe",
    img: "product_3.webp",
    images: [
      "product_3.webp",
      "product_2.webp",
      "product_4.webp",
      "product_5.webp",
    ],
    title: "ბარაქის ხე",
    seoTitle: "baraqis-xe",
    LocId: 3,
    SellerType: 2,
    viewCount: Math.floor(Math.random() * 100) + 1,
    price: Math.floor(Math.random() * 100) + 1,
    description:
      "სერთიფიკატით დამტენილი ორგანიკური მწვანე ფეხი, რომელიც წესების შესახებ ეცადება გადასასვლელად.",
    createdAt: new Date(),
    author: {
      firstName: "გიორგი",
      role: "ფიზიკური პირი",
      phoneNumber: "+995-519-55-66-43",
    },
  },
  {
    id: 4,
    CatId: 5052,
    MainCatId: 5000,
    SubCatId: 5050,
    slug: "/4/5052/wiwvovani-maradmwvane/wiwvovani-maradmwvane/naZvi/naZvis-nergebi",
    img: "product_4.webp",
    images: [
      "product_4.webp",
      "product_2.webp",
      "product_6.webp",
      "product_7.webp",
    ],
    title: "ნაძვის ნერგები",
    seoTitle: "naZvis-nergebi",
    LocId: 4,
    SellerType: 3,
    viewCount: Math.floor(Math.random() * 100) + 1,
    price: Math.floor(Math.random() * 100) + 1,
    description:
      "მიზნალიერებული მწვანე სახლები, რომელიც სადაციანების და გამზირის თვალწინაა.",
    createdAt: new Date(),
    author: {
      firstName: "დათო",
      role: "ფიზიკური პირი",
      phoneNumber: "+995-519-55-66-44",
    },
  },
  {
    id: 5,
    CatId: 4108,
    MainCatId: 4000,
    SubCatId: 4100,
    slug: "/5/4108/yvavilebi/qotnis-yvavilebi/sxva/mcenares-qoTani",
    img: "product_5.webp",
    images: [
      "product_5.webp",
      "product_2.webp",
      "product_3.webp",
      "product_4.webp",
    ],
    title: "მცენარეს ქოთანი",
    seoTitle: "mcenares-qoTani",
    LocId: 5,
    SellerType: 3,
    viewCount: Math.floor(Math.random() * 100) + 1,
    price: Math.floor(Math.random() * 100) + 1,
    description: "შემცველი პროდუქტების მსხვილი შემოტანა და მოძრაობა.",
    createdAt: new Date(),
    author: {
      firstName: "ელენე",
      role: "ფიზიკური პირი",
      phoneNumber: "+995-519-55-66-45",
    },
  },
  {
    id: 6,
    CatId: 6119,
    MainCatId: 6000,
    SubCatId: 6100,
    slug: "/6/6119/chiTilebi-da-saTesle-masala/Tesli/simindi/simindis-saTesle-masala",
    img: "product_6.webp",
    images: [
      "product_6.webp",
      "product_2.webp",
      "product_3.webp",
      "product_4.webp",
    ],
    title: "სიმინდის სათესლე მასალა",
    seoTitle: "simindis-saTesle-masala",
    LocId: 2,
    SellerType: 3,
    viewCount: Math.floor(Math.random() * 100) + 1,
    price: Math.floor(Math.random() * 100) + 1,
    description: "პროდუქტების აღდგენა და მათი დაცვა და გადაგზავნა.",
    createdAt: new Date(),
    author: {
      firstName: "ფრანგი",
      role: "ფიზიკური პირი",
      phoneNumber: "+995-519-55-66-46",
    },
  },
  {
    id: 7,
    CatId: 6125,
    MainCatId: 6000,
    SubCatId: 6100,
    slug: "/7/6125/chiTilebi-da-saTesle-masala/Tesli/sxva/xorbali",
    img: "product_7.webp",
    images: [
      "product_7.webp",
      "product_2.webp",
      "product_3.webp",
      "product_4.webp",
    ],
    title: "ხორბალი",
    seoTitle: "xorbali",
    LocId: 16,
    SellerType: 2,
    viewCount: Math.floor(Math.random() * 100) + 1,
    price: Math.floor(Math.random() * 100) + 1,
    description: "შემცველი პროდუქტების მსხვილი შემოტანა და მოძრაობა.",
    createdAt: new Date(),
    author: {
      firstName: "გრიგოლ",
      role: "მაღაზია",
      phoneNumber: "+995-519-55-66-47",
    },
  },
  {
    id: 8,
    CatId: 10056,
    MainCatId: 10000,
    SubCatId: 10050,
    slug: "/8/10056/agro-inventari/meRvineoba/Rvinis-500-litriani-qvevri",
    img: "product_8.webp",
    images: [
      "product_8.webp",
      "product_2.webp",
      "product_3.webp",
      "product_4.webp",
    ],
    title: "ღვინის 500 ლიტრიანი ქვევრი",
    seoTitle: "Rvinis-500-litriani-qvevri",
    LocId: 5,
    SellerType: 2,
    viewCount: Math.floor(Math.random() * 100) + 1,
    price: Math.floor(Math.random() * 100) + 1,
    description: "უმაღლესი ხარისხის პროდუქტების გამოყენება.",
    createdAt: new Date(),
    author: {
      firstName: "ჰენრი",
      role: "მაღაზია",
      phoneNumber: "+995-519-55-66-48",
    },
  },
  {
    id: 9,
    CatId: 10052,
    MainCatId: 10000,
    SubCatId: 10050,
    slug: "/9/10052/mcenareebis-movlis-saSualebebi/agro-inventari/eleqtronuli-motori/wylis-tumbo-pompa",
    img: "product_9.webp",
    images: [
      "product_9.webp",
      "product_2.webp",
      "product_3.webp",
      "product_4.webp",
    ],
    title: "წყლის ტუმბო/პომპა",
    seoTitle: "wylis-tumbo-pompa",
    LocId: 5,
    SellerType: 2,
    viewCount: Math.floor(Math.random() * 100) + 1,
    price: Math.floor(Math.random() * 100) + 1,
    description: "გადასვლა საგემოსათვის, მორეული გზების შექმნა.",
    createdAt: new Date(),
    author: {
      firstName: "ირაკლი",
      role: "მაღაზია",
      phoneNumber: "+995-519-55-66-49",
    },
  },
  {
    id: 10,
    CatId: 1052,
    MainCatId: 1000,
    SubCatId: 1050,
    slug: "/10/1052/cxovelebi-da-frinvelebi/cxovelebi/Zroxa/saxare-xboebi",
    img: "product_10.webp",
    images: [
      "product_10.webp",
      "product_12.webp",
      "product_5.webp",
      "product_4.webp",
    ],
    title: "სახარე ხბოები",
    seoTitle: "saxare-xboebi",
    LocId: 7,
    SellerType: 2,
    viewCount: Math.floor(Math.random() * 100) + 1,
    price: Math.floor(Math.random() * 100) + 1,
    description: "მოძრაობა და გადასვლა საგემოსათვის, რაც გამოიწვევს შექმნას.",
    createdAt: new Date(),
    author: {
      firstName: "ჯაკო",
      role: "მაღაზია",
      phoneNumber: "+995-519-55-66-40",
    },
  },
  {
    id: 11,
    CatId: 1101,
    MainCatId: 1000,
    SubCatId: 1100,
    slug: "/11/1101/cxovelebi-da-frinvelebi/frinvelebi/qaTami/limonisferi-koxinxini",
    img: "product_11.webp",
    images: [
      "product_11.webp",
      "product_12.webp",
      "product_4.webp",
      "product_3.webp",
      "product_2.webp",
      "product_7.webp",
      "product_8.webp",
    ],
    title: "ლიმონისფერი კოხინხინი",
    seoTitle: "limonisferi-koxinxini",
    LocId: 7,
    SellerType: 2,
    viewCount: Math.floor(Math.random() * 100) + 1,
    price: Math.floor(Math.random() * 100) + 1,
    description: "მოძრაობა და გადასვლა საგემოსათვის, რაც გამოიწვევს შექმნას.",
    createdAt: new Date(),
    author: {
      firstName: "ჯაკო",
      role: "მაღაზია",
      phoneNumber: "+995-519-55-66-14",
    },
  },
  {
    id: 12,
    CatId: 1056,
    MainCatId: 1000,
    SubCatId: 1050,
    slug: "/12/1056/cxovelebi-da-frinvelebi/cxovelebi/Rori/bekonis-goWebi",
    img: "product_12.webp",
    images: [
      "product_12.webp",
      "product_1.webp",
      "product_3.webp",
      "product_4.webp",
    ],
    title: "ბეკონის გოჭები",
    seoTitle: "bekonis-goWebi",
    LocId: 7,
    SellerType: 2,
    viewCount: Math.floor(Math.random() * 100) + 1,
    price: Math.floor(Math.random() * 100) + 1,
    description: "მოძრაობა და გადასვლა საგემოსათვის, რაც გამოიწვევს შექმნას.",
    createdAt: new Date(),
    author: {
      firstName: "ჯაკო",
      role: "მაღაზია",
      phoneNumber: "+995-519-55-66-24",
    },
  },
];

export const blogPosts = [
  {
    title: "5 რჩევა სიმინდის თესვისთვის",
    description: "5 რამ, რაც სიმინდის თესვამდე, აუცილებლად უნდა გაითვალისწინოთ",
    createdAt: new Date(),
    img: "blog_1.webp",
  },
  {
    title: "ნიადაგის ნიმუშის აღების ინსტრუქცია საანალიზოდ",
    description:
      "ანალიზის შედეგებისა და რეკომენდაციების სანდოობა, პირველ რიგში, დამოკიდებულია პირველ ეტაპზე, კერძოდ ნიმუშის აღებაზე. ნიმუშის აღება შეიძლება განვიხილოთ სამ მარტივ ეტაპად",
    createdAt: new Date(),
    img: "blog_2.webp",
  },
  {
    title: "არათანაბარი განაწილება - პივოტური სარწყავი სისტემები",
    description:
      "ირიგაციის სისტემის მოსაწყობად, თქვენ საკმაოდ დიდ ინვესტიციას იღებთ და მისი დანიშნულებაა, თქვენი ნაკვეთიდან მაქსიმალური ეკონომიკური შემოსავლები მიიღოთ. თუმცა",
    createdAt: new Date(),
    img: "blog_3.webp",
  },
  {
    title: "პესტიციდების დადებითი შედეგები",
    description:
      "მიწასთან მომუშავე ფერმერისა თუ გლეხის ყოველდღიური საქმიანობის უმთავრესი მიზანი უხვი და ჯანსაღი მოსავლის მიღებაა. სხვადასხვა კულტურის სიჯანსაღესა და მოსავლიანობას ხელს უშლის განსხვავებული დაავადებები და მავნებლები, მათთან საბრძოლველად კი ყველაზე ეფექტური გზა მცენარეთა დაცვის საშუალებების გამოყენებაა.",
    createdAt: new Date(),
    img: "blog_4.webp",
  },
  {
    title: "ჩაი ევროპის ბაზარზე (ექსპორტის გზამკვლევი)",
    description:
      "სურსათის უვნებლობის და გარემოს დაცვის მოთხოვნებთან შესაბამისობაში მყოფი, სერტიფიცირებული ჩაის წილი",
    createdAt: new Date(),
    img: "blog_5.webp",
  },
  {
    title: "რა განსხვავებაა ჰიბრიდსა და გენმოდიფიცირებულს შორის?",
    description:
      "გაიგე რა განსხვავებაა ჰიბრიდულ და გენმოდიფიცირებულ სათერსლე მასალას შორის, გაეცანი ჩვენს ბლოგს ამ საკითხზე",
    createdAt: new Date(),
    img: "blog_6.webp",
  },
];

export const TEMP_IMAGE_ROOT = "/";
